# Static completions are generated by apply. Shell startup only adds the cache
# to fpath and initializes Zsh's local completion cache; it never runs a tool's
# generator, package manager, or network operation.
_dotfiles_completion_dir="${XDG_CACHE_HOME:-$HOME/.cache}/dotfiles/completions/zsh"
_dotfiles_zcompdump="${XDG_STATE_HOME:-$HOME/.local/state}/zsh/zcompdump"

if [[ -d "$_dotfiles_completion_dir" ]]; then
  fpath=("$_dotfiles_completion_dir" $fpath)
fi
autoload -Uz compinit
compinit -d "$_dotfiles_zcompdump"

unset _dotfiles_completion_dir _dotfiles_zcompdump
