#!/usr/bin/env bash

DOTFILES_COMPLETION_MARKER="# Generated by dotfiles; do not edit."

completion_command_path() {
  local command_name="$1" path_entry candidate
  local old_ifs="$IFS"
  IFS=:
  for path_entry in $PATH; do
    [[ -n "$path_entry" ]] || path_entry=.
    candidate="$path_entry/$command_name"
    [[ -x "$candidate" && ! -d "$candidate" ]] || continue

    # The managed gh shim delegates through 1Password and must never be used
    # to generate public shell-completion code. Find the package-manager binary
    # later on PATH instead.
    if [[ "$command_name" == "gh" && "$candidate" == "$HOME/.local/bin/gh" ]]; then
      continue
    fi
    IFS="$old_ifs"
    printf '%s\n' "$candidate"
    return 0
  done
  IFS="$old_ifs"
  return 1
}

static_completion_is_managed() {
  local destination="$1"
  [[ -f "$destination" && ! -L "$destination" ]] || return 1
  sed -n '1,3p' "$destination" | grep -Fqx -- "$DOTFILES_COMPLETION_MARKER"
}

ensure_static_zsh_completion() {
  local label="$1" completion_name="$2" command_name="$3"
  shift 3
  local destination="$DOTFILES_CACHE_HOME/completions/zsh/_$completion_name"
  local pretty parent executable raw generated first_line
  pretty="$(dotfiles_pretty_path "$destination")"
  parent="$(dirname -- "$destination")"

  if [[ -e "$destination" || -L "$destination" ]]; then
    if ! static_completion_is_managed "$destination"; then
      report_conflict "$pretty exists but is not dotfiles-generated completion state"
      return 1
    fi
  fi

  if [[ "${DOTFILES_DRY_RUN:-0}" == "1" ]]; then
    report_add configure "reconcile $label Zsh completion at $pretty (only if generated output changed)"
    return 0
  fi

  executable="$(completion_command_path "$command_name" 2>/dev/null || true)"
  if [[ -z "$executable" ]]; then
    report_conflict "$label completion generator is unavailable after package reconciliation"
    return 1
  fi
  if [[ ! -d "$parent" ]]; then
    report_conflict "$pretty parent directory is unavailable"
    return 1
  fi

  raw="$(mktemp "${TMPDIR:-/tmp}/dotfiles-completion-raw.XXXXXX")"
  generated="$(mktemp "$parent/.dotfiles-completion.XXXXXX")"
  if ! "$executable" "$@" >"$raw"; then
    rm -f "$raw" "$generated"
    report_conflict "$label failed to generate Zsh completion"
    return 1
  fi
  if [[ ! -s "$raw" ]]; then
    rm -f "$raw" "$generated"
    report_conflict "$label generated an empty Zsh completion"
    return 1
  fi

  IFS= read -r first_line <"$raw" || true
  {
    printf '%s\n' "$first_line"
    printf '%s\n' "$DOTFILES_COMPLETION_MARKER"
    sed '1d' "$raw"
  } >"$generated"
  rm -f "$raw"

  if [[ -f "$destination" ]] && cmp -s "$generated" "$destination"; then
    rm -f "$generated"
    report_add unchanged "$pretty"
    return 0
  fi

  chmod 644 "$generated"
  mv "$generated" "$destination"
  report_add changed "generated $label Zsh completion at $pretty"
}
