[tools]
node = "lts"
bun = "latest"
pnpm = "latest"
go = "latest"
python = "latest"
ruby = "latest"
rust = "stable"
terraform = "latest"

[settings]
idiomatic_version_file_enable_tools = [
  "node",
  "bun",
  "pnpm",
  "python",
  "ruby",
  "rust",
  "terraform",
]
